In [1]:
import numpy as np

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

Y = np.array([
    [0],
    [0],
    [0],
    [1]
])


X = X.T
Y = Y.T

layers = [X.shape[0],2,5,1]

In [2]:
def init_params(layers):
    params = {}
    for L in range(1,len(layers)):
        params['W'+str(L)] = np.random.randn(layers[L],layers[L-1])*0.1
        params['b'+str(L)] = np.zeros((layers[L],1))
    return params

In [3]:
def foward_prop(A,params,layers,cache):
    for L in range(1,len(layers)):
        A_prev = A
        cache['Z'+str(L)] = np.dot(params['W'+str(L)],A_prev) + params['b'+str(L)]
        cache['A'+str(L)] = 1/(1+np.exp(-cache['Z'+str(L)]))
        A = cache['A'+str(L)]
    return cache

In [4]:
def backprop(layers,params,Y,cache):
    gradients = {}
    L = len(layers)-1
    m = Y.shape[1]
    gradients['dZ'+str(L)] = cache['A'+str(L)] - Y
    gradients['dW'+str(L)] = np.dot(gradients['dZ'+str(L)],cache['A'+str(L-1)].T)/m
    gradients['db'+str(L)] = np.sum(gradients['dZ'+str(L)],axis=1,keepdims=True)/m
    
    for L in reversed(range(L)):
        if L != 0:          
            gradients['dA'+str(L)] = np.dot(params['W'+str(L+1)].T, gradients['dZ'+str(L+1)])
            gradients['dZ'+str(L)] = np.multiply(gradients['dA'+str(L)], np.int64(cache['A'+str(L)] > 0))
            gradients['dW'+str(L)] = 1. / m * np.dot(gradients['dZ'+str(L)], cache['A'+str(L-1)].T)
            gradients['db'+str(L)] = 1. / m * np.sum(gradients['dZ'+str(L)], axis=1, keepdims=True)
    return gradients

In [166]:
def update_params(layers,params,gradients):
    L = len(layers) - 1
    for L in range(1,L):
        params['W'+str(L)] = params['W'+str(L)] - 0.01*gradients['dW'+str(L)]
        params['b'+str(L)] = params['b'+str(L)] - 0.01*gradients['db'+str(L)]
    return params

In [168]:
params = init_params(layers)
cache = {}
cache['A0'] = X

for i in range(4000):
    prev_params = params
    cache  = foward_prop(X,prev_params,layers,cache)
    gradients = backprop(layers,prev_params,Y,cache)
    params = update_params(layers,prev_params,gradients)
    
    if i%200 == 0:
        print(cache['A2'])
    

[[0.46910987 0.46700196 0.4698519  0.46774436]]
[[0.46826636 0.46622761 0.46907055 0.46702941]]
[[0.46742734 0.46546147 0.46829424 0.46632298]]
[[0.46659405 0.46470442 0.46752395 0.4656257 ]]
[[0.4657677  0.46395725 0.4667606  0.46493816]]
[[0.46494944 0.4632207  0.46600504 0.46426087]]
[[0.46414035 0.46249545 0.46525809 0.46359428]]
[[0.46334146 0.46178211 0.46452051 0.46293882]]
[[0.46255371 0.46108123 0.46379297 0.46229483]]
[[0.46177799 0.46039328 0.46307613 0.46166261]]
[[0.46101511 0.4597187  0.46237056 0.46104242]]
[[0.4602658  0.45905784 0.46167677 0.46043446]]
[[0.45953072 0.45841101 0.46099522 0.45983889]]
[[0.45881047 0.45777846 0.46032632 0.45925584]]
[[0.45810553 0.45716038 0.45967042 0.45868537]]
[[0.45741636 0.45655692 0.4590278  0.45812754]]
[[0.45674332 0.45596818 0.45839871 0.45758236]]
[[0.45608671 0.45539421 0.45778335 0.4570498 ]]
[[0.45544676 0.45483502 0.45718187 0.45652982]]
[[0.45482364 0.45429059 0.45659437 0.45602234]]
