### Getting Matrices right for b and W
    For Example:
    m = number of features = 2
    n = number of samples  = 10
    The shape of W = (n,m)

In [1]:
import numpy as np

In [26]:
w = np.array([[1,2,3],[1,2,3]])
x = np.array([[1,4],[2,5],[3,6]])
np.dot(w,x)

array([[14, 32],
       [14, 32]])

In [27]:
w.shape

(2, 3)

In [28]:
x.shape

(3, 2)

In [7]:
w = np.array([1,2,3])
x = np.array([[1],[2],[3]])
np.dot(w,x)

array([14])

In [20]:
w = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1],[2],[3]])
np.dot(w.T,x)+b
#x.shape

array([[ 67,  79,  91],
       [ 80,  95, 110],
       [ 93, 111, 129]])

In [2]:
# W = np.array([[1],[2]])
# X = np.array([[3],[4]])
# b = 2
# X.dot(W.T) + b

In [3]:
# n = 3
# m = 2

# W = np.random.randn(n,m)
# X = np.random.randn(n,m)
# b = np.random.randn(n)

# X.dot(W.T)

In [4]:
def train(X,Y):
    n = X.shape[0]
    m = X.shape[1]
    
    W = np.random.randn(n,1)
    b = np.random.randn(1,n)
    
    for i in range(1):
        z  = np.dot(W.T,X)
        A  = 1/(1+np.exp(-z))
        dz = A-Y
        
        dw = (1/m)*np.dot(X,dz.T)
        db = (1/m)*np.sum(dz)
        
        W = W - 0.001*dw
        b = b - 0.001*db
        
    return W,b
        
def predict(X,W,b):
    W = W.reshape(4, 1)
    z  = np.dot(W.T,X)
    A  = 1/(1+np.exp(-z))
    return A

In [5]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = np.array([[0,1],[1,0],[1,0],[0,1]])
W,b = train(X,y)
print(W.shape)
#print(predict([[0,0,1]],W,b))

(4, 4)


In [6]:
w, b, X, Y = np.array([[1], [2]]), 2, np.array([[1,2], [3,4]]), np.array([[1, 0]])
print("W.shape = ",w.shape)
#print("b.shape = ",b.shape)
print("X.shape = ",X.shape)
print("Y.shape = ",Y.shape)

W.shape =  (2, 1)
X.shape =  (2, 2)
Y.shape =  (1, 2)


In [2]:
import numpy as np

def sigmoid(z):
    s = 1/(1+np.exp(-z))
    return s

In [3]:
def init_W_b(dim):
    b = 0
    w = np.zeros(shape=(dim))
    return w,b

In [8]:
def propagate(w, b, X, Y):
    m = X.shape[1]
    # Forward prop
    A  = sigmoid(np.dot(w.T,X)+b)
    cost = (- 1 / m) * np.sum(Y * np.log(A) + (1 - Y) * (np.log(1 - A)))
    # Back prop
    dz = A - Y
    dw = (1 / m) * np.dot(X, dz.T)
    db = (1 / m) * np.sum(dz)
    
    # gradients cache
    cost = np.squeeze(cost)
    grads = {"dw": dw,"db": db}
    
    return grads,cost

In [11]:
w = np.array([[1], [2]])
b = 2
X = np.array([[1,2], [3,4]])
Y = np.array([[1, 0]])

In [14]:
w.shape

(2, 1)

In [15]:
X.shape

(2, 2)

In [16]:
Y.shape

(1, 2)

In [12]:
grads, cost = propagate(w, b, X, Y)

In [17]:
print("dw = " + str(grads["dw"]))
print("db = " + str(grads["db"]))
print("cost = " + str(cost))

dw = [[0.99993216]
 [1.99980262]]
db = 0.49993523062470574
cost = 6.000064773192205
